#!/bin/bash

cd "$(dirname "$0")/.." || exit 1

main() {
    preamble > src/optic.txt
    tools/domains | rules >> src/optic.txt
}

preamble() {
    echo 'DiscardNonMatching;'
    cat tools/10k-short.optic
}

rules() {
    echo 'Rule {'
    while read domain; do
        echo 'Matches{Site("|'"${domain}"'|")},'
        echo 'Matches{Like(Site("'"${domain}"'"))},'
    done
    echo '};'
}

main