#!/bin/bash

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"/..

# some domains are "quarantined" - we allow links to specific pages
# within them, but not links to that domain in general. Specific
# allowed pages are listed in leechblock-allowlist.txt
QUARANTINED_REGEX='youtube.com'

(
  # block all URLs by default
  echo "*"

  # generate allowlist from links
  "$REPO_ROOT"/tools/domains \
    | (while read domain; do
      if [ "$domain" == "" ]; then
        continue
      fi

      echo "+$domain"
      if [ "$(<<<"$domain" tr -cd .)" == . ] || <<<"$domain" grep -q '^www\.'; then
        # this is an apex domain
        <<<"$domain" sed -E 's/^(www\.)?/+*./'
      fi
    done) \
    | grep -v "$QUARANTINED_REGEX"

  # append explicit allowlist
  cat "$REPO_ROOT"/tools/leechblock-allowlist.txt
) > "$REPO_ROOT"/src/leechblock.txt