#!/bin/bash

MOSTLY_HARMLESS='bastionhome\.github\.io'\
'|benchristel\.github\.io/meditation'\
'|benchristel\.com/portal\.html'\
'|mail\.google\.com'

echo -n "Pages visited:   "
cat "$@" | \
  ag -v "$MOSTLY_HARMLESS" \
  | wc -l

echo -n "Domains visited: "
cat "$@" | ag -v "$MOSTLY_HARMLESS" \
  | grep -o --no-filename -P 'https?://[^/]+' \
  | sort | uniq | wc -l

echo -n "Google searches: "
cat "$@" | ag 'https://(www\.)?google.com/search' | wc -l

echo -n "DDG searches:    "
cat "$@" | ag duckduckgo.com  | sed -e 's/&ia=web//' | uniq | wc -l
