#!/bin/bash

# Removes domains from src/unlinked-domains.txt that are actually linked from
# markdown files in src/.

cd "$(dirname "$0")/.." || exit 1

find src -name '*.md' \
  | xargs grep -Pro --no-filename 'https?://[^\]\)"\s]+' \
  | tools/domains \
  | diff -U9999 - <(cat src/unlinked-domains.txt | tools/domains) \
  | grep '^+' \
  | grep -v '^+++' \
  | sed -e 's|^+|https://|' \
  | rev | sort | rev > /tmp/unlinked-domains.txt \
  && mv /tmp/unlinked-domains.txt src/unlinked-domains.txt
